-include $(BUILD_ROOT)/ROS/fprime_ws/src/fprime/mod.mk

EXTRA_INC_DIRS_ROSRosTime_DARWIN := $(EXTRA_INC_DIRS_ROSRosTime_DARWIN) $(EXTRA_INC_DIRS_DARWIN) $(EXTRA_INC_DIRS)
EXTRA_LIBS_ROSRosTime_DARWIN := $(EXTRA_LIBS_ROSRosTime_DARWIN) $(EXTRA_LIBS_DARWIN) $(EXTRA_LIBS)

EXTRA_INC_DIRS_ROSRosTime_SDFLIGHT := $(EXTRA_INC_DIRS_ROSRosTime_SDFLIGHT) $(EXTRA_INC_DIRS_SDFLIGHT) $(EXTRA_INC_DIRS)
EXTRA_LIBS_ROSRosTime_SDFLIGHT := $(EXTRA_LIBS_ROSRosTime_SDFLIGHT) $(EXTRA_LIBS_SDFLIGHT) $(EXTRA_LIBS)

EXTRA_INC_DIRS_ROSRosTime_LINUX := $(EXTRA_INC_DIRS_ROSRosTime_LINUX) $(EXTRA_INC_DIRS_LINUX) $(EXTRA_INC_DIRS)
EXTRA_LIBS_ROSRosTime_LINUX := $(EXTRA_LIBS_ROSRosTime_LINUX) $(EXTRA_LIBS_LINUX) $(EXTRA_LIBS)

EXTRA_INC_DIRS_DARWIN=
EXTRA_LIBS_DARWIN=
EXTRA_INC_DIRS_SDFLIGHT=
EXTRA_LIBS_SDFLIGHT=
EXTRA_INC_DIRS_LINUX=
EXTRA_LIBS_LINUX=
EXTRA_INC_DIRS=
EXTRA_LIBS=
