/*
 * ShortLogQueueComponentImplCfg.hpp
 *
 *  Created on: Aug 19, 2017
 *      Author: tim
 */

#ifndef LLPROC_SHORTLOGQUEUE_SHORTLOGQUEUECOMPONENTIMPLCFG_HPP_
#define LLPROC_SHORTLOGQUEUE_SHORTLOGQUEUECOMPONENTIMPLCFG_HPP_

namespace LLProc {
    static const NATIVE_UINT_TYPE SHORT_LOG_QUEUE_DEPTH = 100;
}

#endif /* LLPROC_SHORTLOGQUEUE_SHORTLOGQUEUECOMPONENTIMPLCFG_HPP_ */
