#!/bin/sh
cd ${BUILD_ROOT}/SnapdragonFlight/SnapdragonHealth/test/ut
echo "Running ${BUILD_ROOT}/SnapdragonFlight/SnapdragonHealth/test/ut/$1/test_ut"
${BUILD_ROOT}/SnapdragonFlight/SnapdragonHealth/test/ut/$1/test_ut

