-include $(BUILD_ROOT)/SnapdragonFlight/MVVislam/inc.mk

EXTRA_INC_DIRS_SnapdragonFlightMVVislam_DARWIN := $(EXTRA_INC_DIRS_SnapdragonFlightMVVislam_DARWIN) $(EXTRA_INC_DIRS_DARWIN) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SnapdragonFlightMVVislam_DARWIN := $(EXTRA_LIBS_SnapdragonFlightMVVislam_DARWIN) $(EXTRA_LIBS_DARWIN) $(EXTRA_LIBS)

EXTRA_INC_DIRS_SnapdragonFlightMVVislam_SDFLIGHT := $(EXTRA_INC_DIRS_SnapdragonFlightMVVislam_SDFLIGHT) $(EXTRA_INC_DIRS_SDFLIGHT) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SnapdragonFlightMVVislam_SDFLIGHT := $(EXTRA_LIBS_SnapdragonFlightMVVislam_SDFLIGHT) $(EXTRA_LIBS_SDFLIGHT) $(EXTRA_LIBS)

EXTRA_INC_DIRS_SnapdragonFlightMVVislam_LINUX := $(EXTRA_INC_DIRS_SnapdragonFlightMVVislam_LINUX) $(EXTRA_INC_DIRS_LINUX) $(EXTRA_INC_DIRS)
EXTRA_LIBS_SnapdragonFlightMVVislam_LINUX := $(EXTRA_LIBS_SnapdragonFlightMVVislam_LINUX) $(EXTRA_LIBS_LINUX) $(EXTRA_LIBS)

EXTRA_INC_DIRS_DARWIN=
EXTRA_LIBS_DARWIN=
EXTRA_INC_DIRS_SDFLIGHT=
EXTRA_LIBS_SDFLIGHT=
EXTRA_INC_DIRS_LINUX=
EXTRA_LIBS_LINUX=
EXTRA_INC_DIRS=
EXTRA_LIBS=
